### ISSUE TITLE
WARNING:root:You are using solc version 0.7.6. The supported version is 0.4.21.

### ISSUE THREAD

**Issue by davidloz** [smartbugs/smartbugs#120]
I was running SmartBugs with this contract: 0x0a76C7913C94F2AF16958FbDF9b4CF0bBdb159d8

With the tool Osiris I got the following error:

WARNING:root:You are using solc version 0.7.6. The supported version is 0.4.21.
CRITICAL:root:Solidity compilation failed

Is this an issue with SmartBugs or with the used tool Osiris?

**Comment by gsalzer** [comment]
Thanks for reporting the issue. There are several problems involved.
- The contract contains a rather unconventional version information: 
```solidity
pragma solidity =0.6.11 >=0.6.0 <0.8.0 >=0.6.2 <0.8.0;
```
We use `py-solc-x` to load an appropriate version of the compiler, but it fails to parse this pragma correctly. I reported the issue and proposed a fix, see https://github.com/iamdefinitelyahuman/py-solc-x/issues/147

- The correct version of the compiler, `0.6.11.`, is beyond the supported versions of Osiris (which it tells by a WARNING like the one in your output). But this is just a warning, Osiris will try to go on.
- Solidity `0.6.11` generates textual output that Osiris handles incorrectly (because of a trailing space in certain lines). I tweaked Smartbugs to modify Solidities output to a format that Osiris accepts, but ...
- Osiris finally fails, because the runtime code of the contract contains EVM instructions beyond what Osiris can handle (they were added after the publication of Osiris). Because of problems like this, Osiris issued the WARNING in the beginning.

*Bottomline:* Even when the bugs in solcx get fixed and the minor issue with Solidities output is taken care of, Osiris fails. So either use other tools to analyze this contract, or port the contract to Solidity version 0.4.21.
