### ISSUE TITLE
Questions about datasets

### ISSUE THREAD

**Issue by yagol2020** [smartbugs/smartbugs#124]
https://github.com/smartbugs/smartbugs/blob/e05d324ff0bf5a70594bf14a5ae80d1d63bb7fc5/dataset/reentrancy/spank_chain_payment.sol#L426

The report([link](https://medium.com/swlh/how-spankchain-got-hacked-af65b933393c)) say that EVM's `transfer()` function carries 2,300 gas and does not trigger reentrancy vulnerability. But 426 lines in the dataset are said to contain vulnerabilities.
Please let me know if I understand anything wrong.

**Comment by gsalzer** [comment]
@yagol2020 Can you please recheck your example whether it really illustrates your point? I tried the eleven tools integrated in smartbugs (`-t all`) on this contract (`-f dataset/reentrancy/spank_chain_payment.sol`), and only `conkas` notes that there might be a reentrancy (though in the wrong contract of the file). So the tools actually do not detect the reentrancy vulnerability. This is not surprising, as the tools detect only *some* vulnerabilities, not all.

In any case, the behavior of the tools has nothing to do with Smartbugs, which just supports the user in running the individual tools. If you find that some tool does not work well, you might try the issue tracker of this particular tool.

Just to be precise: The EVM does not offer any transfer function and does not limit the gas by itself (other that you cannot use more than the EOA provided in the beginning). On EVM level, there is just the `call` instruction that transfers Ether in a way that the callee can do mischief. (The instruction `selfdestruct` also transfers Ether, but without invoking any code.) Solidity offers the methods `transfer` and `send` for variables of type `address`, and translates them to `call`s with just 2300 gas.

**Comment by yagol2020** [comment]
@gsalzer 
Thanks for your reply.
I know `transfer` with 2300 gas. Actually, I didn't run the individual tools in smartbugs, just looked at the [dataset](https://github.com/smartbugs/smartbugs/tree/e05d324ff0bf5a70594bf14a5ae80d1d63bb7fc5/dataset) in smartbugs. My question is that line 426 uses the `transfer` , does it contain a reentrancy vulnerability? Are there false positives in the dataset?

**Comment by gsalzer** [comment]
I'm not the author of these datasets, maybe @jff can comment on it. I think that most contracts in the data sets actually have a weakness in one way or the other, but there is a difference between a weakness (something that might be exploited), an actual vulnerability (there is an exploit), and patterns that can be actually detected by tools.
In the contract that you are referring to, the reentrancy attack proceeds via the call to the `transfer` function in line `430`. An attacker may submit the address of a contract that has the interface of a token contract but actually does a callback. The money is drained via the `transfer` in line `426`. Since this is a normal transfer, 2300 gas is sufficient. The reentrancy loop happens via line 430, and there, the gas is not constrained. I don't think that there are many tools around that are able to detect this reentrancy attack.

**Comment by yagol2020** [comment]
@gsalzer 
Yes, as you said, reentrancy happens via line `430`. I don't think the reentrancy vulnerability can occur with 426 lines, **maybe** there is a problem with the labels of the dataset.
