### ISSUE TITLE
Cannot get solc, where should I install the compiler

### ISSUE THREAD

**Issue by smartcontract-detect-yzu** [smartbugs/smartbugs#138]
![image](https://user-images.githubusercontent.com/71329338/206943244-ea8ff46b-ee29-46e6-a5ec-0a3a34a158f6.png)

**Comment by gsalzer** [comment]
Thanks for reporting the issue. It is a permission problem related to the fact that you run smartbugs with `sudo`. Maybe SB stores the compiler in a different place than it later thinks it is. I will check it out.
HOWEVER: running `smartbugs` as `root` (because of the `sudo` command) is not a good idea anyway, since any of the scripts invoked by Smartbugs, including itself, may delete or change anything in the system. It shouldn't, but who knows ...
Just omit `sudo`. If you encounter permission problems because you are not allowed to write to the current directory, go to a working directory where you have write permissions, and then run
```bash
~/work/smartbugs/smartbugs -t mythril -f ~/work/smartbugs:samples/*.sol
```

One reason you might have chosen to run `smartbugs` as root might be the interaction with docker. In this case, it is better to add the user running smartbugs to the `docker` group. 
```bash
sudo usermod -a -G docker lighthouse
```
Then you have to load the new group membership; the easiest way to do so is to login anew.

**Comment by smartcontract-detect-yzu** [comment]
thanks for your kindly rely, it works for me. For add the user to the docker group, we do like:
```
sudo usermod -aG docker $USER
newgrp docker
```
