### ISSUE TITLE
Use Oyente's json output

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#22]
Following [Xiao Liang's comment](https://github.com/smartbugs/smartbugs/pull/17#issuecomment-656201244), Smartbugs could use Oyente's Json interface instead of the currently output parser.

**Comment by yxliang01** [comment]
Great! I am currently maintaining Oyente. If anyone encounters issues with the json interface, please feel free to create an issue in Oyente repo. So far, for my other projects, it works well.

**Comment by jff** [comment]
Smartbugs 2.0 fixes this. @gsalzer

**Comment by gsalzer** [comment]
> Smartbugs 2.0 fixes this. @gsalzer

@jff  Ok with closing the issue, but SB 2.0 does not pick up this suggestion. Currently, Osiris, Honeybadger and Oyente all use the same output parser, since the first two tools are modifications of Oyente and generate similar output. I don't think, however, that they also implement Oyente's `web` option. For the time being, I prefer to have just one parser for all three. If, in the future, we discover that it makes sense to fork the parser code, we can use Oyente's json output fot the Oyente parser.
