### ISSUE TITLE
Pragma version in solidity contract is incorrect

### ISSUE THREAD

**Issue by nveloso** [smartbugs/smartbugs#23]
Hi! The contract **0xec329ffc97d75fe03428ae155fc7793431487f63.sol** has a typo in pragma version.

The current pragma is `pragma solidity >=0.4.11;` but it fails to compile with solc version 0.5.0 or higher.

A possible fix could be to change the pragma version to this `pragma solidity ^0.4.11;`.

PS: This contract is from the unchecked_low_level_calls dataset

**Comment by jff** [comment]
Thanks, @nveloso!

This contract was extracted _as is_ from Etherscan ([link](https://etherscan.io/address/0xec329ffc97d75fe03428ae155fc7793431487f63#code).

I think we can update the pragma, but we need to decide if it is necessary to document these changes. @pedrocrvz might have an opinion on this :)

**Comment by pedrocrvz** [comment]
> The current pragma is `pragma solidity >=0.4.11;` but it fails to compile with solc version 0.5.0 or higher.
> 

Actually, I **think** `>=` doesn't set an upper limit (`^` does), on the compiler version. So if it doesn't compile it should be because of [breaking changes](https://solidity.readthedocs.io/en/v0.5.0/050-breaking-changes.html). (We added some disclaimer to the[ README.md](https://github.com/smartbugs/smartbugs#known-limitations) about versioning issues)

> A possible fix could be to change the pragma version to this `pragma solidity ^0.4.11;`.

`pragma solidity ^0.4.11;` should not work as `^0.4.11` means that it will compile with a compiler version `>= 0.4.11` and `< 0.5.0`. ([docs](https://solidity.readthedocs.io/en/v0.4.0/layout-of-source-files.html)) 


> I think we can update the pragma, but we need to decide if it is necessary to document these changes. @pedrocrvz might have an opinion on this :)

I am ok with updating the pragma versions, but I would keep it _as is_. Other contracts may also have breaking changes if they are not compiled with the right version. Plus, vulnerabilities can be patched in more recent compiler versions and IMO we should guarantee that contracts retrieved from the blockchain and added to the dataset remain  _as is_.

**Comment by nveloso** [comment]
I understand that the contracts should remain as is since they were retrieved from the blockchain. However, if a tool compiles that contract based on the pragma version it would not verify that contract because the compilation fails, missing vulnerabilities in that contract.

**Comment by jff** [comment]
I am in favour of not changing contracts in the dataset, so that they remain faithful to their sources. In my view, the two acceptable solutions for this problem are:

1. The analysis tool knows how to deal with pragma versions (thus becoming a more robust tool)
2. SmartBugs can have an option that does that for tools who do not support the feature mention in point 1

**Comment by pedrocrvz** [comment]
> * The analysis tool knows how to deal with pragma versions (thus becoming a more robust tool)

SmartBugs already does this for v4 and v5. If I remember correctly, if the `.yaml` file contains both version of the tools it will choose the correct one to run. i.e if the version is below is below v5 and there is defined a docker image in the `.yaml` file for it, it will run that image - if not it will run the default. (see [line](https://github.com/smartbugs/smartbugs/blob/master/src/docker_api/docker_api.py#L220))

We need to update it to also be aware of newer versions.

**Comment by jff** [comment]
Yes, my point was that it could be optional. And it would be good to revise/update it!

**Comment by TanmayT** [comment]
I am also facing the same issue...any updates on this?

**Comment by jff** [comment]
@TanmayT Could you provide more details about the issue you are having? We are planning to revise SmartBugs' version management soon and it would be helpful to understand the different contexts in which this problem might occur.

**Comment by cesarvspr** [comment]
Is the any solutions for this? I can't properly run the test using all tools due to some erro relate to compiler and contract version

**Comment by gsalzer** [comment]
The current smartbugs, master branch, commit 190f18b0448acc314572b55365e98d0f994fda07, the issues mentioned in this thread seem to be resolved.
- version pragmas of the form `>=0.` are rewritten to `^0.` before searching for a suitable compiler version.
- Since version 1.1, SmartBugs is able to determine the Solidity version from the source code and download the correct compiler.
