### ISSUE TITLE
Bytecode support: add tool EthRacer

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#60]
https://github.com/ashgeek/Ethracer

**Comment by gsalzer** [comment]
@jff `bytecode` is wrong in the help message, it should be `Contract source code`, as described in  [README](https://github.com/ashgeek/Ethracer/blob/master/README.md).

But this file is not essential: you can use "IDoNotExist.sol" as the file name. Ethracer uses `solc` to obtain the mapping from the 4-byte-signatures to the function headers, probably to improve readability of the results, or maybe to improve fuzzing by using the argument types.

The problem is rather that Ethracer uses the address of the contract to obtain the bytecode from the blockchain, which it expects to find at `http://127.0.0.1:8666`. So this means that if we want to check arbitrary bytecode, we would first have to deploy it on the blockchain. This requires deployment code, not runtime code as we have in our repository, and as the other tools use.

Bottomline: Ethracer does not fit our scheme. I suggest to remove it from the list of supported tools.

**Comment by jff** [comment]
Thanks @gsalzer

I'll close this issue
