### ISSUE TITLE
[Clarification] Getting exception when trying to execute "Maian" via smartbug

### ISSUE THREAD

**Issue by sandkan** [smartbugs/smartbugs#85]
Hi there, 
I tried executing the following command 
`python3 smartBugs.py --tool maian --file dataset/reentrancy/simple_dao.sol`

But I am getting the following exception. my docker is running perfectly, i suspect if there is an issue with the image. Or Am i doing something wrong?

![image](https://user-images.githubusercontent.com/88367872/141715281-7016b596-121a-4ea6-8173-364c721d299e.png)

Thanks!
Sandkan

**Comment by limcheekin** [comment]
I'm having the same error here when running smartbugs in GitHub Actions.
It is running fine 2 weeks ago.

**Comment by tdurieux** [comment]
We are working on a new version of smartbugs that is also working with bytecode analysis. We recently updated the image but did not push the changes to the main branch. The code in the bytecode branch should work properly.

(cc @jff)

**Comment by jff** [comment]
Hi @sandkan and @limcheekin , thanks for reporting this. As @tdurieux explained, we updated the docker image, since we are in the process of releasing a new version of Smartbugs. As a temporary workaround, you can replace the file `config/tools/maian.yaml` with this one https://github.com/smartbugs/smartbugs/blob/bytecode/config/tools/maian.yaml

If the problem persists, please let us know.

**Comment by limcheekin** [comment]
Thanks for quick response. Any doc for new features of the new version of Smartbugs?
